# Default values for frontend chart
replicaCount: 1

image:
  repository: nextapp
  tag: "1.0.2"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 3000

# Environment variables
env:
  NEXT_PUBLIC_API_URL: "http://{{ .Release.Name }}-backend:8000"

# Resource limits
resources:
  limits:
    cpu: 300m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi

# Pod security context
securityContext: {}

# Container security context
containerSecurityContext: {}

# Liveness and readiness probes
livenessProbe:
  enabled: true
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 6
  successThreshold: 1
  path: /api/health

readinessProbe:
  enabled: true
  initialDelaySeconds: 5
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 6
  successThreshold: 1
  path: /api/health


# Ingress configuration 
ingress:
  enabled: false  # with 'enabled' set to 'false' Helm will not create an Ingress object anyway
  className: ""
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []