apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "backend.fullname" . }}-env-file
  labels:
    {{- include "backend.labels" . | nindent 4 }}
data:
  .env: |
    POSTGRES_USER={{ .Values.database.user }}
    POSTGRES_PASSWORD={{ .Values.database.password }}
    POSTGRES_DB={{ .Values.database.name }}
    DATABASE_URL=postgres://{{ .Values.database.user }}:{{ .Values.database.password }}@{{ include "postgres.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local:5432/{{ .Values.database.name }}?sslmode=disable