replicaCount: 1

image:
  repository: tankengine/goapp
  tag: "1.0.1"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8000

# Resource limits
resources:
  limits:
    cpu: 500m # one-thousandth of a CPU core. For example, 500m is equivalent to 0.5 CPU cores
    memory: 512Mi  # "Mi" stands for "Mebibyte"
  requests:
    cpu: 50m
    memory: 128Mi

securityContext: {}

containerSecurityContext: {}

livenessProbe:
  enabled: true
  initialDelaySeconds: 60  # increased from 30
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 6
  successThreshold: 1
  path: /health

readinessProbe:
  enabled: true
  initialDelaySeconds: 20  # increased from 5
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 6
  successThreshold: 1
  path: /health

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

serviceAccount:
  create: true
  name: "property-app-backend"
  annotations: {}

vault:
  enabled: true
  role: "postgres-role"
  secretPath: "property-app/database"

  podAnnotations:
    vault.hashicorp.com/agent-inject: "true"
    vault.hashicorp.com/agent-init-first: "true" 
    traffic.sidecar.istio.io/excludeOutboundPorts: "8200"
    proxy.istio.io/config: '{"holdApplicationUntilProxyStarts": true}'
    vault.hashicorp.com/role: "postgres-role"
    vault.hashicorp.com/address: "http://vault.vault.svc.cluster.local:8200" # CHANGED: Removed /cluster.local
    vault.hashicorp.com/agent-inject-secret-database-config: "property-app/database"
    vault.hashicorp.com/agent-inject-template-database-config: |
      {{- with secret "property-app/database" -}}
      #!/bin/sh
      export DATABASE_URL="postgres://{{ .Data.data.user }}:{{ .Data.data.password }}@property-app-postgres.property-app.svc.cluster.local:5432/{{ .Data.data.database }}?sslmode=disable"
      {{- end -}}

  # Database configuration (used to build the .env file)
database:
  user: ""    # Will be overridden by parent chart
  password: ""
  name: ""