replicaCount: 1

image:
  repository: tankengine/goapp
  tag: "1.0.4"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8000

# Resource limits
resources:
  limits:
    cpu: 500m # one-thousandth of a CPU core. For example, 500m is equivalent to 0.5 CPU cores
    memory: 512Mi  # "Mi" stands for "Mebibyte"
  requests:
    cpu: 50m
    memory: 128Mi

securityContext: {}

containerSecurityContext: {}

livenessProbe:
  enabled: true
  initialDelaySeconds: 60  # increased from 30
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 6
  successThreshold: 1
  path: /health

readinessProbe:
  enabled: true
  initialDelaySeconds: 20  # increased from 5
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 6
  successThreshold: 1
  path: /health

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

serviceAccount:
  create: true
  name: "property-app-backend"
  annotations: {}

vault:
  enabled: true
  role: "postgres-role"
  secretPath: "property-app/database"

podAnnotations: {}

  # Database configuration (used to build the .env file)
database:
  user: ""    # Will be overridden by parent chart
  password: ""
  name: ""