# Default values for postgres chart

# These fields allow chart users to override naming without modifying templates
# nameOverride: ""
# fullnameOverride: ""

replicaCount: 1

image:
  repository: postgres
  tag: "15"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 5432

persistence:
  enabled: false
  storageClass: "local-storage"
  accessMode: ReadWriteOnce
  size: 8Gi

database:
  name: propertydb
  user: pguser
  password: pgpassword

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 256Mi

securityContext:
  fsGroup: 999

containerSecurityContext:
  runAsUser: 999
  runAsNonRoot: true

livenessProbe:
  enabled: true
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 6
  successThreshold: 1

readinessProbe:
  enabled: true
  initialDelaySeconds: 5
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 6
  successThreshold: 1

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []