---
- name: Copy join command to worker
  copy:
    src: /tmp/joincommand.sh
    dest: /home/ubuntu/joincommand.sh
    mode: '0755'

- name: Join the worker node to the cluster
  shell: |
    /home/ubuntu/joincommand.sh
  register: join_result
  changed_when: join_result.rc == 0
  failed_when: join_result.rc != 0 and "already exists" not in join_result.stderr