apiVersion: v1
kind: Secret
metadata:
  name: {{ include "postgres.fullname" . }}-credentials
  labels:
    {{- include "postgres.labels" . | nindent 4 }}
type: Opaque
data:
  postgres-user: {{ .Values.database.user | b64enc | quote }}
  postgres-password: {{ .Values.database.password | b64enc | quote }}
  postgres-db: {{ .Values.database.name | b64enc | quote }}