apiVersion: v1
kind: Secret
metadata:
  name: {{ include "postgres.fullname" . }}-configuration
  labels:
    {{- include "postgres.labels" . | nindent 4 }}
type: Opaque
data:
  # Note: Database credentials are now managed by HashiCorp Vault
  # Only non-sensitive configuration remains here
