
global:
  environment: development


postgres:
  # Note: Actual credentials are now stored in HashiCorp Vault
  database:
    name: "propertydb"  # This is now just a placeholder/reference
    # user and password fields removed - now managed by Vault
  
  # New Vault configuration
  vault:
    enabled: true
    role: "postgres-role"
    secretPath: "postgres/data/config"
  
  persistence:
    enabled: true
    storageClass: "local-storage"
    accessMode: ReadWriteOnce
    size: 8Gi
  
  resources:
    limits:
      cpu: 200m
      memory: 300Mi
    requests:
      cpu: 50m
      memory: 150Mi
  
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 3
    targetCPUUtilizationPercentage: 80

backend:
  enabled: true
  
  # Actual credentials are now stored in HashiCorp Vault
  database:
    name: "propertydb"  # This is now just a placeholder/reference
    # user and password fields removed - now managed by Vault
  
  vault:
    enabled: true
    role: "postgres-role"
    secretPath: "postgres/data/config"
    
  # You can add annotations for the backend deployment to use 
  # the same Vault credentials if needed
  podAnnotations:
    vault.hashicorp.com/agent-inject: "true"
    vault.hashicorp.com/role: "postgres-role"
    vault.hashicorp.com/agent-inject-secret-database-config: "postgres/data/config"
    vault.hashicorp.com/agent-inject-template-database-config: |
      {{- with secret "postgres/data/config" -}}
      DATABASE_URL=postgres://{{ .data.data.user }}:{{ .data.data.password }}@property-app-postgres.property-app.svc.cluster.local:5432/{{ .data.data.database }}?sslmode=disable
      {{- end -}}
  
  resources:
    limits:
      cpu: 200m
      memory: 300Mi
    requests:
      cpu: 50m
      memory: 150Mi
  
  livenessProbe:
    enabled: true
    path: /health
    initialDelaySeconds: 60
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 6
    successThreshold: 1
  
  readinessProbe:
    enabled: true
    path: /health
    initialDelaySeconds: 20
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 6
    successThreshold: 1
  
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 3
    targetCPUUtilizationPercentage: 80

frontend:
  env:
    NEXT_PUBLIC_API_URL: "http://13.51.86.244/api"
  ingress:
    enabled: false
  
  resources:
    limits:
      cpu: 200m
      memory: 200Mi
    requests:
      cpu: 50m
      memory: 100Mi
  
  livenessProbe:
    enabled: true
    path: /api/health
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 6
    successThreshold: 1
  
  readinessProbe:
    enabled: true
    path: /api/health
    initialDelaySeconds: 5
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 6
    successThreshold: 1
  
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 3
    targetCPUUtilizationPercentage: 80