# Global values shared across all subcharts
global:
  environment: development

# Enable or disable subcharts
postgres:
  enabled: true
  # Override postgres subchart values
  database:
    name: "propertydb"
    user: "pguser"
    password: "pgpassword"

  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 3
    targetCPUUtilizationPercentage: 80

backend:
  enabled: true
  # Database configuration for the backend
  database:
    name: "propertydb"
    user: "pguser"
    password: "pgpassword"
  
  # You can remove the env section as we'll use the ConfigMap instead
  
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 3
    targetCPUUtilizationPercentage: 80

frontend:
  enabled: true
  # Override frontend subchart values
  env:
    NEXT_PUBLIC_API_URL: "http://{{ .Release.Name }}-backend:8000"

  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 3
    targetCPUUtilizationPercentage: 80