# Global values shared across all subcharts
global:
  environment: development

# Enable or disable subcharts
postgres:
  enabled: true
  # Database configuration
  database:
    name: "propertydb"
    user: "pguser"
    password: "pgpassword"  # In production, use a secret reference
  
  # Persistence configuration
  persistence:
    enabled: true
    storageClass: "local-storage"
    accessMode: ReadWriteOnce
    size: 8Gi
  
  # Resource settings
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 256Mi
  
  # Scaling
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 3
    targetCPUUtilizationPercentage: 80

backend:
  enabled: true
  
  # Database configuration for backend to connect to postgres
  database:
    name: "propertydb"
    user: "pguser"
    password: "pgpassword"  # In production, use a secret reference
  
  # Resource settings
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 128Mi
  
  # Health checks
  livenessProbe:
    enabled: true
    path: /health
    initialDelaySeconds: 60
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 6
    successThreshold: 1
  
  readinessProbe:
    enabled: true
    path: /health
    initialDelaySeconds: 20
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 6
    successThreshold: 1
  
  # Scaling
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 3
    targetCPUUtilizationPercentage: 80

frontend:
  enabled: true
  
  # API URL configuration - this will properly set the environment variable 
  env:
    NEXT_PUBLIC_API_URL: "http://{{ .Release.Name }}-backend:8000"
  
  # Resource settings
  resources:
    limits:
      cpu: 300m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 128Mi
  
  # Health checks
  livenessProbe:
    enabled: true
    path: /api/health
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 6
    successThreshold: 1
  
  readinessProbe:
    enabled: true
    path: /api/health
    initialDelaySeconds: 5
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 6
    successThreshold: 1
  
  # Scaling
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 3
    targetCPUUtilizationPercentage: 80