postgres:
  serviceAccount:
    create: false
    name: "property-app-postgres"
  
  vault:
    enabled: true
    role: "postgres-role"
    secretPath: "postgres/config"
  
  podAnnotations:
    vault.hashicorp.com/agent-inject: "true"
    vault.hashicorp.com/role: "postgres-role"
    vault.hashicorp.com/agent-inject-secret-postgres-creds: "postgres/config"
    vault.hashicorp.com/address: "http://vault.vault:8200" 
    vault.hashicorp.com/agent-inject-template-postgres-creds: |
      {{- with secret "postgres/config" -}}
      #!/bin/sh
      export POSTGRES_USER="{{ .Data.data.user }}"
      export POSTGRES_PASSWORD="{{ .Data.data.password }}"
      export POSTGRES_DB="{{ .Data.data.database }}"
      {{- end -}}
  
  extraInitContainers:
    - name: init-postgres-scripts
      image: busybox
      command: ['sh', '-c', 'ls -la /vault/secrets/ && if [ -f /vault/secrets/postgres-creds ]; then cp /vault/secrets/postgres-creds /docker-entrypoint-initdb.d/init-db.sh && chmod +x /docker-entrypoint-initdb.d/init-db.sh; echo "File copied successfully"; else echo "Source file does not exist"; exit 1; fi']
      volumeMounts:
        - name: init-scripts
          mountPath: /docker-entrypoint-initdb.d
  
  extraVolumes:
    - name: init-scripts
      emptyDir: {}
  
  extraVolumeMounts:
    - name: init-scripts
      mountPath: /docker-entrypoint-initdb.d

backend:
  serviceAccount:
    create: true
    name: "property-app-backend"
  
  vault:
    enabled: true
    role: "postgres-role"
    secretPath: "postgres/config"
  
  podAnnotations:
    vault.hashicorp.com/agent-inject: "true"
    vault.hashicorp.com/role: "postgres-role"
    vault.hashicorp.com/agent-inject-secret-database-config: "postgres/config"  # Remove "data" from path
    vault.hashicorp.com/address: "http://vault.vault:8200" 
    vault.hashicorp.com/agent-inject-template-database-config: |
      {{- with secret "postgres/config" -}}  # Match the path used above
      #!/bin/sh
      export DATABASE_URL="postgres://{{ .Data.data.user }}:{{ .Data.data.password }}@property-app-postgres.property-app.svc.cluster.local:5432/{{ .Data.data.database }}?sslmode=disable"
      {{- end -}}